baseURL: https://toolchained.github.io
languageCode: en-us
title: My New Hugo Site
theme: ananke

permalinks:
  posts: /:year/:month/:title/

# github.com/theNewDynamic/gohugo-theme-ananke
# Submodule 'themes/universal' (https://github.com/devcows/hugo-universal-theme.git) registered for path 'themes/universal'
# Submodule 'themes/yourfolio' (https://github.com/serg/yourfolio.git) registered for path 'themes/yourfolio'